name: build-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - run: echo "Building artifacts for ${{ github.ref_name }}"
      - uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          files: |
            LICENSE
            README.md
          draft: false
          prerelease: false
