name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '25 7 * * 1'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: "Run OpenSSF Scorecard"
        uses: ossf/scorecard-action@ff5dd8929f96a8a4dc67d13f32b8c75057829621
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload to SARIF"
        uses: github/codeql-action/upload-sarif@6d786de4d6f3531a740e445b53a42b622bbbace8
        with:
          sarif_file: results.sarif
